---
settings:
  name: Astra Automation 21.12
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr
sidebar:
  entries:
  - title: Astra Control Automation 21.12 - Dokumentation
    url: "/index.html"
  - section: rn
  - section: intro
  - section: get-started
  - section: rest-core
  - section: additional
  - section: endpoints
  - section: workflows_infra
  - section: workflows
  - section: python
  - section: reference
  - section: information
  - title: Frühere Versionen
    url: "/aa-earlier-versions.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Einführung
      summary: Verschaffen Sie sich einen Überblick über die Astra REST API.
      url: "/intro/introduction.html"
    - title: Bevor Sie beginnen
      summary: Die Verwendung der REST API wird vorbereitet.
      url: "/get-started/before_get_started.html"
    - title: Holen Sie sich ein API-Token
      summary: Erstellen Sie ein Token, das Sie für den Zugriff auf die API benötigen.
      url: "/get-started/get_api_token.html"
    - title: Hallo Welt
      summary: Testen Sie den grundlegenden Zugriff auf die REST-API.
      url: "/get-started/hello_world.html"
  - title: REST-Implementierung
    links:
    - title: REST-Web-Services
      summary: Die Technologie-Grundlagen DER REST-Web-Services verstehen.
      url: "/rest-core/rest_web_services.html"
    - title: HTTP-Details
      summary: Überprüfen Sie die Details der HTTP-Implementierung.
      url: "/rest-core/http_details.html"
    - title: URL-Format
      summary: Verstehen Sie das URL-Format und wie es aus mehreren Werten besteht.
      url: "/rest-core/url_format.html"
  - title: Weitere Überlegungen
    links:
    - title: Sicherheit
      summary: Entdecken Sie die mit DER REST API bereitgestellten Sicherheitsfunktionen.
      url: "/additional/security.html"
    - title: Arbeiten mit Sammlungen
      summary: Verwenden Sie Abfrageparameter, um auf die Ressourcensammlungen zuzugreifen.
      url: "/additional/working_with_collections.html"
    - title: Diagnose und Support
      summary: Vorbereitung auf die Unterstützung von Astra-Applikationen
      url: "/additional/diagnostics_support.html"
  - title: Ressourcen
    links:
    - title: Ressourcen und Sammlungen
      summary: Machen Sie sich mit dem Design VON REST-Ressourcen und -Sammlungen
        vertraut.
      url: "/rest-core/resources_collections.html"
    - title: Astra Control REST-API-Ressourcen
      summary: Lesen Sie eine kurze Einführung in die verschiedenen Astra-Ressourcen.
      url: "/endpoints/resources.html"
  - title: Workflows
    links:
    - title: Vorbereitung
      summary: Die Astra-Workflows werden vorbereitet.
      url: "/get-started/prepare_to_use_workflows.html"
    - title: Infrastruktur-Workflows
      summary: Die erforderlichen Workflows für die Wartung der Astra Runtime-Infrastruktur.
      url: "/workflows_infra/workflows_infra_before.html"
    - title: Management-Workflows
      summary: Die geläufigeren Workflows, die zum Verwalten der gemanagten Applikationen
        verwendet werden.
      url: "/workflows/workflows_before.html"
  - title: Python
    links:
    - title: Bevor Sie beginnen
      summary: Vorbereiten, um die Python-Beispielskripte auszuführen.
      url: "/python/python_before.html"
    - title: Listen Sie die verwalteten Apps auf
      summary: Führen Sie ein Beispielskript aus, um die verwalteten Apps aufzulisten.
      url: "/python/py_list_man_apps.html"
